name: Deploy GitHub Pull Request Pages

on:
  push:
    branches:
      - main
  # pull_request_target:
  #   types:
  #     - closed

jobs:
  build:
    # if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'pull-request-tutorial')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install and Build
        run: |
          cd github-pull-request
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          publish_dir: ./github-pull-request/dist
