name: Deploy GitHub Pull Request Pages

on:
  push:
    branches:
      - main
  # pull_request_target:
  #   types:
  #     - closed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    # if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'pull-request-tutorial')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          path: ./github-pull-request
          node-version: 20
          package-manager: pnpm
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
